### ISSUE TITLE
Fanboying

### ISSUE THREAD

**Issue by Coopez** [lcordes/bci#1]
OMG, I love this!
This is the best repo I have seen on github to date.
The documentation is impeccable and so intuitive!
AMAZING!

**Comment by Coopez** [comment]
Btw, did you delete all of your code by destroying your VM?

**Comment by lcordes** [comment]
I will not tolerate such slanderous rumors in my repository

**Comment by lcordes** [comment]
I will not tolerate such slanderous rumors in my repository!
